### ISSUE TITLE
Nothing plays

### ISSUE THREAD

**Issue by cerinthus** [Twoure/9anime.bundle#9]
As per title.

[com.plexapp.plugins.9anime.log.zip](https://github.com/Twoure/9anime.bundle/files/1008683/com.plexapp.plugins.9anime.log.zip)

**Comment by Twoure** [comment]
Fixed in https://github.com/Twoure/9anime.bundle/commit/caaa8c3be31f1026e870a1c738cdf8babb6c26d3

**Comment by nswali** [comment]
Nothing play for me too. Have removed both plugin and data and reinstalled the latest dev bundle, but I still get the following exceptions:

2017-05-18 10:57:41,669 (-e4a84c0) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/serviceFunction/url/com.plexapp.plugins.9anime/9anime/PlayVideo?args=Y2VyZWFsMQoxCnR1cGxlCjAKcjAK&kwargs=Y2VyZWFsMQoxCmRpY3QKMgpzNTUKaHR0cHM6Ly85YW5pbWUudG8vd2F0Y2gvY3liZXItY2l0eS1vZWRvLTgwOC4zbHFyL3Y5Nnh2NHMzCnVybHM0CjEwODBzMwpyZXNyMAo_&indirect=1&mediaInfo=%7B%22audio_channels%22%3A%202%2C%20%22protocol%22%3A%20null%2C%20%22optimized_for_streaming%22%3A%20true%2C%20%22video_frame_rate%22%3A%20null%2C%20%22duration%22%3A%20null%2C%20%22height%22%3A%201080%2C%20%22width%22%3A%201920%2C%20%22container%22%3A%20%22mp4%22%2C%20%22audio_codec%22%3A%20%22aac%22%2C%20%22aspect_ratio%22%3A%20null%2C%20%22video_codec%22%3A%20%22h264%22%2C%20%22video_resolution%22%3A%20%221080%22%2C%20%22bitrate%22%3A%20null%7D
2017-05-18 10:57:41,674 (-e4a84c0) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/serviceFunction/url/com.plexapp.plugins.9anime/9anime/PlayVideo
2017-05-18 10:57:41,839 (-e4a84c0) :  DEBUG (network:76) - * Caching 'https://9anime.to/token' to DataHTTP
2017-05-18 10:57:41,847 (-e4a84c0) :  DEBUG (network:128) - JSFDecoder failed, falling back to exejs >>> JSFDecoder: No JSF code found
2017-05-18 10:57:42,163 (-e4a84c0) :  CRITICAL (network:138) - * <network.Request[error]>: Cannot handle token cookie >>> (most recent call last):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/9anime.bundle/Contents/Services/Shared Code/network.pys", line 134, in get_cookies
    t = ctx.exec_('return jssuckit')
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/9anime.bundle/Contents/Libraries/Shared/execjs/_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/9anime.bundle/Contents/Libraries/Shared/execjs/_external_runtime.py", line 83, in _exec_
    return self._extract_result(output)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/9anime.bundle/Contents/Libraries/Shared/execjs/_external_runtime.py", line 165, in _extract_result
    raise exceptions.ProgramError(value)
ProgramError: ReferenceError: window is not defined

2017-05-18 10:57:42,164 (-e4a84c0) :  INFO (ServiceCode:87) - * 9anime Cookies for https://9anime.to/watch/cyber-city-oedo-808.3lqr/v96xv4

2017-05-18 10:57:42,311 (-e4a84c0) :  DEBUG (network:76) - * Caching 'https://9anime.to/ajax/episode/info?id=v96xv4' to DataHTTP
2017-05-18 10:57:42,318 (-e4a84c0) :  CRITICAL (sandbox:303) - Exception when calling function 'PlayVideo' (most recent call last):
  File "/volume4/@appstore/Plex Media Server/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 294, in call_named_function
    result = f(*args, **kwargs)
  File "/volume4/@appstore/Plex Media Server/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 85, in __call__
    return self._f(*args, **kwargs)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/9anime.bundle/Contents/Services/URL/9anime/ServiceCode.pys", line 92, in PlayVideo
    grabber = clean_url(data['grabber'] + '?' + urlencode(data['params']))
  File "/volume4/@appstore/Plex Media Server/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
KeyError: 'grabber'

2017-05-18 10:57:42,320 (-e4a84c0) :  CRITICAL (runtime:889) - Exception (most recent call last):
  File "/volume4/@appstore/Plex Media Server/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request
    result = f(**d)
  File "/volume4/@appstore/Plex Media Server/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/handlers/services.py", line 150, in call_service_function
    result = self._core.services._call_named_function_in_service(f_name, service, f_args, f_kwargs)
  File "/volume4/@appstore/Plex Media Server/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/services.py", line 589, in _call_named_function_in_service
    return self._call_named_function_in_sandbox(service.sandbox, fname, None, f_args, f_kwargs, allow_deferred, raise_exceptions, f_optional)
  File "/volume4/@appstore/Plex Media Server/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/services.py", line 573, in _call_named_function_in_sandbox
    result = sandbox.call_named_function(fname, allow_deferred=allow_deferred, raise_exceptions=raise_exceptions, args=f_args, kwargs=f_kwargs, mod_name=mod_name, optional_kwargs=f_optional)
  File "/volume4/@appstore/Plex Media Server/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 294, in call_named_function
    result = f(*args, **kwargs)
  File "/volume4/@appstore/Plex Media Server/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 85, in __call__
    return self._f(*args, **kwargs)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/9anime.bundle/Contents/Services/URL/9anime/ServiceCode.pys", line 92, in PlayVideo
    grabber = clean_url(data['grabber'] + '?' + urlencode(data['params']))
  File "/volume4/@appstore/Plex Media Server/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
KeyError: 'grabber'

2017-05-18 10:57:42,323 (-e4a84c0) :  DEBUG (runtime:88) - Sending packed state data (99 bytes)
2017-05-18 10:57:42,324 (-e4a84c0) :  DEBUG (runtime:924) - Response: [500] 2353 bytes
2017-05-18 10:57:46,066 (-e4a84c0) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/messaging/function/X1N0b3JlU2VydmljZTpJc0NoYW5uZWxCcm9rZW4_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMQpzMjYKY29tLnBsZXhhcHAucGx1Z2lucy45YW5pbWVzMTAKaWRlbnRpZmllcnIwCg__
2017-05-18 10:57:46,068 (-e4a84c0) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2017-05-18 10:57:46,071 (-e4a84c0) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/messaging/function/X1N0b3JlU2VydmljZTpJc0NoYW5uZWxCcm9rZW4_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMQpzMjYKY29tLnBsZXhhcHAucGx1Z2lucy45YW5pbWVzMTAKaWRlbnRpZmllcnIwCg__
2017-05-18 10:57:46,074 (-e4a84c0) :  DEBUG (runtime:88) - Sending packed state data (99 bytes)
2017-05-18 10:57:46,074 (-e4a84c0) :  DEBUG (runtime:924) - Response: [200] str, 32 bytes
2017-05-18 10:57:47,155 (-e4a84c0) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/messaging/function/X1N0b3JlU2VydmljZTpJc0NoYW5uZWxCcm9rZW4_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMQpzMjYKY29tLnBsZXhhcHAucGx1Z2lucy45YW5pbWVzMTAKaWRlbnRpZmllcnIwCg__
2017-05-18 10:57:47,158 (-e4a84c0) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2017-05-18 10:57:47,161 (-e4a84c0) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/messaging/function/X1N0b3JlU2VydmljZTpJc0NoYW5uZWxCcm9rZW4_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMQpzMjYKY29tLnBsZXhhcHAucGx1Z2lucy45YW5pbWVzMTAKaWRlbnRpZmllcnIwCg__
2017-05-18 10:57:47,164 (-e4a84c0) :  DEBUG (runtime:88) - Sending packed state data (99 bytes)
2017-05-18 10:57:47,164 (-e4a84c0) :  DEBUG (runtime:924) - Response: [200] str, 32 bytes
2017-05-18 10:57:57,283 (-e4a84c0) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/messaging/function/X1N0b3JlU2VydmljZTpJc0NoYW5uZWxCcm9rZW4_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMQpzMjYKY29tLnBsZXhhcHAucGx1Z2lucy45YW5pbWVzMTAKaWRlbnRpZmllcnIwCg__
2017-05-18 10:57:57,285 (-e4a84c0) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2017-05-18 10:57:57,287 (-e4a84c0) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/messaging/function/X1N0b3JlU2VydmljZTpJc0NoYW5uZWxCcm9rZW4_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMQpzMjYKY29tLnBsZXhhcHAucGx1Z2lucy45YW5pbWVzMTAKaWRlbnRpZmllcnIwCg__
2017-05-18 10:57:57,290 (-e4a84c0) :  DEBUG (runtime:88) - Sending packed state data (99 bytes)
2017-05-18 10:57:57,291 (-e4a84c0) :  DEBUG (runtime:924) - Response: [200] str, 32 bytes
2017-05-18 10:57:58,359 (-e4a84c0) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/messaging/function/X1N0b3JlU2VydmljZTpJc0NoYW5uZWxCcm9rZW4_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMQpzMjYKY29tLnBsZXhhcHAucGx1Z2lucy45YW5pbWVzMTAKaWRlbnRpZmllcnIwCg__
2017-05-18 10:57:58,361 (-e4a84c0) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2017-05-18 10:57:58,363 (-e4a84c0) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/messaging/function/X1N0b3JlU2VydmljZTpJc0NoYW5uZWxCcm9rZW4_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMQpzMjYKY29tLnBsZXhhcHAucGx1Z2lucy45YW5pbWVzMTAKaWRlbnRpZmllcnIwCg__
2017-05-18 10:57:58,366 (-e4a84c0) :  DEBUG (runtime:88) - Sending packed state data (99 bytes)
2017-05-18 10:57:58,366 (-e4a84c0) :  DEBUG (runtime:924) - Response: [200] str, 32 bytes
2017-05-18 10:58:01,008 (-e4a84c0) :  DEBUG (runtime:717) - Handling request GET /system/services/url/lookup?url=https%3A%2F%2F9anime.to%2Fwatch%2Fcyber-city-oedo-808.3lqr%2Fv96xv4
2017-05-18 10:58:01,013 (-e4a84c0) :  DEBUG (runtime:814) - Found route matching /system/services/url/lookup
2017-05-18 10:58:01,014 (-e4a84c0) :  DEBUG (services:23) - Looking up URL 'https://9anime.to/watch/cyber-city-oedo-808.3lqr/v96xv4'
2017-05-18 10:58:01,016 (-e4a84c0) :  DEBUG (services:616) - Found a service matching 'https://9anime.to/watch/cyber-city-oedo-808.3lqr/v96xv4' - 9anime (com.plexapp.plugins.9anime)
2017-05-18 10:58:01,021 (-e4a84c0) :  DEBUG (services:616) - Found a service matching 'https://9anime.to/watch/cyber-city-oedo-808.3lqr/v96xv4' - 9anime (com.plexapp.plugins.9anime)
2017-05-18 10:58:01,027 (-e4a84c0) :  DEBUG (network:106) - * Fetching 'https://9anime.to/watch/cyber-city-oedo-808.3lqr/v96xv4' from DataHTTP
2017-05-18 10:58:01,052 (-e4a84c0) :  DEBUG (preferences:178) - Reloaded the user preferences for com.plexapp.plugins.9anime
2017-05-18 10:58:01,053 (-e4a84c0) :  INFO (metadata:160) - * found for S0E3 on server 1
2017-05-18 10:58:01,054 (-e4a84c0) :  INFO (ServiceCode:37) - * ep_dict = {'epn': '3', 'season': 0, 'server': 1, 'href': '/watch/cyber-city-oedo-808.3lqr/v96xv4', 'title': u'S0E3'}
2017-05-18 10:58:01,075 (-e4a84c0) :  DEBUG (services:30) - TAG: Object
2017-05-18 10:58:01,085 (-e4a84c0) :  DEBUG (services:616) - Found a service matching 'https://9anime.to/watch/cyber-city-oedo-808.3lqr/v96xv4' - 9anime (com.plexapp.plugins.9anime)
2017-05-18 10:58:01,093 (-e4a84c0) :  DEBUG (runtime:88) - Sending packed state data (99 bytes)
2017-05-18 10:58:01,093 (-e4a84c0) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 6901 bytes
2017-05-18 10:58:02,492 (-e4a84c0) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/serviceFunction/url/com.plexapp.plugins.9anime/9anime/PlayVideo?args=Y2VyZWFsMQoxCnR1cGxlCjAKcjAK&kwargs=Y2VyZWFsMQoxCmRpY3QKMgpzNTUKaHR0cHM6Ly85YW5pbWUudG8vd2F0Y2gvY3liZXItY2l0eS1vZWRvLTgwOC4zbHFyL3Y5Nnh2NHMzCnVybHM0CjEwODBzMwpyZXNyMAo_&indirect=1&mediaInfo=%7B%22audio_channels%22%3A%202%2C%20%22protocol%22%3A%20null%2C%20%22optimized_for_streaming%22%3A%20true%2C%20%22video_frame_rate%22%3A%20null%2C%20%22duration%22%3A%20null%2C%20%22height%22%3A%201080%2C%20%22width%22%3A%201920%2C%20%22container%22%3A%20%22mp4%22%2C%20%22audio_codec%22%3A%20%22aac%22%2C%20%22aspect_ratio%22%3A%20null%2C%20%22video_codec%22%3A%20%22h264%22%2C%20%22video_resolution%22%3A%20%221080%22%2C%20%22bitrate%22%3A%20null%7D
2017-05-18 10:58:02,497 (-e4a84c0) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/serviceFunction/url/com.plexapp.plugins.9anime/9anime/PlayVideo
2017-05-18 10:58:02,503 (-e4a84c0) :  DEBUG (network:106) - * Fetching 'https://9anime.to/token' from DataHTTP
2017-05-18 10:58:02,509 (-e4a84c0) :  DEBUG (network:128) - JSFDecoder failed, falling back to exejs >>> JSFDecoder: No JSF code found
2017-05-18 10:58:02,827 (-e4a84c0) :  CRITICAL (network:138) - * <network.Request[error]>: Cannot handle token cookie >>> (most recent call last):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/9anime.bundle/Contents/Services/Shared Code/network.pys", line 134, in get_cookies
    t = ctx.exec_('return jssuckit')
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/9anime.bundle/Contents/Libraries/Shared/execjs/_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/9anime.bundle/Contents/Libraries/Shared/execjs/_external_runtime.py", line 83, in _exec_
    return self._extract_result(output)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/9anime.bundle/Contents/Libraries/Shared/execjs/_external_runtime.py", line 165, in _extract_result
    raise exceptions.ProgramError(value)
ProgramError: ReferenceError: window is not defined

2017-05-18 10:58:02,829 (-e4a84c0) :  INFO (ServiceCode:87) - * 9anime Cookies for https://9anime.to/watch/cyber-city-oedo-808.3lqr/v96xv4

2017-05-18 10:58:02,831 (-e4a84c0) :  DEBUG (network:106) - * Fetching 'https://9anime.to/ajax/episode/info?id=v96xv4' from DataHTTP
2017-05-18 10:58:02,837 (-e4a84c0) :  CRITICAL (sandbox:303) - Exception when calling function 'PlayVideo' (most recent call last):
  File "/volume4/@appstore/Plex Media Server/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 294, in call_named_function
    result = f(*args, **kwargs)
  File "/volume4/@appstore/Plex Media Server/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 85, in __call__
    return self._f(*args, **kwargs)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/9anime.bundle/Contents/Services/URL/9anime/ServiceCode.pys", line 92, in PlayVideo
    grabber = clean_url(data['grabber'] + '?' + urlencode(data['params']))
  File "/volume4/@appstore/Plex Media Server/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
KeyError: 'grabber'

2017-05-18 10:58:02,839 (-e4a84c0) :  CRITICAL (runtime:889) - Exception (most recent call last):
  File "/volume4/@appstore/Plex Media Server/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request
    result = f(**d)
  File "/volume4/@appstore/Plex Media Server/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/handlers/services.py", line 150, in call_service_function
    result = self._core.services._call_named_function_in_service(f_name, service, f_args, f_kwargs)
  File "/volume4/@appstore/Plex Media Server/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/services.py", line 589, in _call_named_function_in_service
    return self._call_named_function_in_sandbox(service.sandbox, fname, None, f_args, f_kwargs, allow_deferred, raise_exceptions, f_optional)
  File "/volume4/@appstore/Plex Media Server/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/services.py", line 573, in _call_named_function_in_sandbox
    result = sandbox.call_named_function(fname, allow_deferred=allow_deferred, raise_exceptions=raise_exceptions, args=f_args, kwargs=f_kwargs, mod_name=mod_name, optional_kwargs=f_optional)
  File "/volume4/@appstore/Plex Media Server/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 294, in call_named_function
    result = f(*args, **kwargs)
  File "/volume4/@appstore/Plex Media Server/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 85, in __call__
    return self._f(*args, **kwargs)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/9anime.bundle/Contents/Services/URL/9anime/ServiceCode.pys", line 92, in PlayVideo
    grabber = clean_url(data['grabber'] + '?' + urlencode(data['params']))
  File "/volume4/@appstore/Plex Media Server/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
KeyError: 'grabber'

**Comment by Twoure** [comment]
Site changed again. Will look into when I get time.

**Comment by Twoure** [comment]
Fixed in https://github.com/Twoure/9anime.bundle/commit/fb08f54b14ec099795c6d2deced960705251febb

**Comment by nswali** [comment]
Thanks for the quick turnaround - plays fine now.

**Comment by IJ08** [comment]
@nswali works fine for you? was it latest dev branch? did you do anything else asides from updated using latest dev?

**Comment by Twoure** [comment]
Site changed again, will look into when I have time.

**Comment by IJ08** [comment]
Thanks! They change sites more often now.

**Comment by cerinthus** [comment]
Sorry, was away from my computer so couldn't check.

Works a treat now.  Can be closed.  Thanks

**Comment by IJ08** [comment]
@cerinthus the latest dev branch working for you? the one wherein the changes are related to network.psy?

**Comment by cerinthus** [comment]
Yep.  Working fine.

**Comment by IJ08** [comment]
Thanks I confirm!
